name: CI/CD Pipeline

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: action-runner

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy
        run: |
          rsync -av --delete ./ /home/ec2-user/github-action-ci-cd/
          cd /home/ec2-user/github-action-ci-cd
          npm i
          npm run test
          pm2 restart deafult
